name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

dependencies:
  camera: ^0.10.0+1  # Usa la versión más estable de la librería
  http: ^0.13.6      # Usa la versión de http que has mencionado antes
  path_provider: ^2.0.11  # Necesario si estás utilizando almacenamiento local
  flutter:
    sdk: flutter
  mime: ^2.0.0
  html: ^0.15.6  # Agregar esta dependencia
  google_ml_kit: ^0.10.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"  # Ajusta el rango de la versión del SDK de Dart

flutter:
  uses-material-design: true
